language: dart
dart:
  - stable

jobs:
  include:
    - stage: valid
      name: "Dart Analyzer"
      os: linux
      script: dart --enable-experiment=non-nullable analyze --fatal-warnings --fatal-infos .
    - stage: valid
      name: "Dart Formatter"
      os: linux
      script: dart --enable-experiment=non-nullable format --output=none .
    - stage: test
      name: "VM Tests"
      os: linux
      script: dart --enable-experiment=non-nullable test --platform vm test/all_test.dart
    - stage: test
      name: "Chrome Tests"
      os: linux
      script: dart --enable-experiment=non-nullable test --platform chrome test/all_test.dart

stages:
  - valid
  - test
