name: more
version: 1.10.1

author: Lukas Renggli <renggli@gmail.com>
homepage: https://github.com/renggli/dart-more
description: More Dart â€” Literally. Collecting, iterating, caching, mathematics,
  matching, and ordering easily.

environment:
  sdk: '>=2.0.0-dev.69.0 <3.0.0'
dependencies:
  collection: ^1.14.0
dev_dependencies:
  build_runner: ^0.9.0
  build_test: ^0.10.0
  build_web_compilers: ^0.4.0
  test: ^1.3.0