name: more
version: 1.5.2
author: Lukas Renggli <renggli@gmail.com>
description: More Dart â€” Literally
homepage: https://github.com/renggli/dart-more
environment:
  sdk: ^1.20.0
dev_dependencies:
  test: ^0.12.0
