name: more
version: 4.2.0

homepage: https://github.com/renggli/dart-more
description: More Dart â€” Literally. Collecting, iterating, caching, mathematics,
  matching, ordering, and formatting easily.
topics:
  - collections
  - data-structures
  - functional
  - graph
  - unicode

environment:
  sdk: ^3.3.0
dependencies:
  characters: ^1.3.0
  clock: ^1.1.0
  collection: ^1.18.0
  meta: ^1.11.0
dev_dependencies:
  args: ^2.4.0
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  fake_async: ^1.3.0
  lints: ^3.0.0
  test: ^1.25.0