name: more
version: 1.7.1
author: Lukas Renggli <renggli@gmail.com>
description: More Dart â€” Literally
homepage: https://github.com/renggli/dart-more
environment:
  sdk: '>=1.23.0 <2.0.0'
dev_dependencies:
  test: ^0.12.0
