name: more
version: 2.6.0

homepage: https://github.com/renggli/dart-more
description: More Dart â€” Literally. Collecting, iterating, caching, mathematics,
  matching, ordering, and formatting easily.

environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  characters: ^1.0.0
  collection: ^1.14.0
  meta: ^1.2.0
dev_dependencies:
  test: ^1.15.0
