name: more
version: 3.0.0-nullsafety

homepage: https://github.com/renggli/dart-more
description: More Dart â€” Literally. Collecting, iterating, caching, mathematics,
  matching, ordering, and formatting easily.

environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  characters: ^1.1.0-nullsafety
  clock: ^1.1.0-nullsafety
  collection: ^1.15.0-nullsafety
  meta: ^1.3.0-nullsafety
dev_dependencies:
  fake_async: ^1.2.0-nullsafety
  test: ^1.16.0-nullsafety
