name: more
version: 3.8.2

homepage: https://github.com/renggli/dart-more
description: More Dart â€” Literally. Collecting, iterating, caching, mathematics,
  matching, ordering, and formatting easily.

environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  characters: ^1.2.0
  clock: ^1.1.0
  collection: ^1.16.0
  meta: ^1.7.0
dev_dependencies:
  args: ^2.3.0
  fake_async: ^1.3.0
  lints: ^2.0.0
  test: ^1.21.0
